### ISSUE TITLE
paths with spaces don't work

### ISSUE THREAD

**Issue by Wursthandschuh** [adrifcastr/OSAC#12]
This is windows. Paths have spaces =)
Pls add this feature

**Comment by adrifcastr** [comment]
This is answer.
Paths with spaces are unhealthy and shouldn't be used ever. I can rename the file before conversion tho.

**Comment by thw0rted** [comment]
Can I make a suggestion? If you don't want to add quoting for filename arguments where required (understandable, since this can be a hassle), would you consider adding a check when selecting a file to show the user an error and suggest renaming to remove spaces?  I had to figure this out by copy/pasting from the log window into Notepad and following the console output.  If a user has less technical skill, they're likely to be stumped and wind up coming here to open another issue, or just looking for different software.

**Comment by thw0rted** [comment]
I noticed that [when calling ffprobe](https://github.com/adrifcastr/OSAC/blob/master/OSAC/MainWindow.xaml.cs#L140), the argument is wrapped in double quotes, but [when calling ffmpeg](https://github.com/adrifcastr/OSAC/blob/master/OSAC/MainWindow.xaml.cs#L226) it is not.  I think the error might be resolved if you wrap `fileout` in quotes.

I don't have the build toolchain set up myself at the moment, so I can't actually test a PR, but if I have a little free time over the weekend I might give it a shot.
