### ISSUE TITLE
Filename issue

### ISSUE THREAD

**Issue by demilich1** [adrifcastr/OSAC#9]
First of all I want to say thank you for this useful tool.

I am having a slight issue regarding file names. So I installed the Audible App from the Windows 10 Store and downloaded an audio book. The resulting filename of the specific audio book was 
`Heimatabend Deluxe. _B004V2PZQW_LC_64_44100_Stereo.aax`
I could select the file just fine in OSAC and it seems the DRM cracking also worked. But no output file was generated and there was a console error 
`D:\Audible\Heimatabend: No such file or directory`. 
I think the issue is either the dot in addition to the file extension or the whitespaces.

Renaming the file to 'heimatabend.aax' fixed the issue for me, so this is not a big deal, but it still would be nice if all filenames were properly supported.

**Comment by AraFloFanGurke** [comment]
It's a problem with ffmpeg, because ffmpeg doesn't support spaces in the form: Name Of File.aax, it just uses the form: Name\ Of\ File.aax (the way linux command line uses spaces), so when OSAC gives ffmpeg the input and output file it does not recognize. (In ffmpeg every space means a new option, so when it gets [ffmpeg -i Name Of File.aax] it thinks Name is the input file and Of is a new option again...)
xD

**Comment by thw0rted** [comment]
I suggested under #12 that a warning should be shown when selecting a file name with spaces in the path.  You also might look at using quoted filenames when supplying commandline arguments instead of trying to escape spaces with backslashes; that's how I write most of my own personal ffmpeg scripts in Windows.
